apiVersion: v1
kind: Service
metadata:
  name: todo-project-svc
spec:
  type: ClusterIP
  selector:
    app: todo-project # This is the app as declared in the deployment.
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 3000 # This is the target port
