apiVersion: apps/v1
kind: Deployment
metadata:
  name: uuidgen-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uuidgen
  template:
    metadata:
      labels:
        app: uuidgen
    spec:
      containers:
        - name: uuidgen
          image: tonipikkarainen/first-app
